### PR TITLE
Add predictable and discoverable event names

### PR DESCRIPTION
**Pull request by kraman**

### CODE REVIEW

**Comment by kraman** [comment]
Fixes one aspect of https://github.com/strongloop/async-tracker/issues/1

**Comment by sam-github** [comment]
@piscisaureus PTAL

**Comment by piscisaureus** [comment]
The patch itself lgtm, but I wonder what async methods on objects will be named (e.g. the stream.write method, or the child process 'exit' event).

**Comment by piscisaureus** [comment]
In that sense, I wonder if adding the method `AsyncTracker.prototype.generateEventName` is really that useful. Unless you're planning on extending the method later, it seems that just writing `"fs.write"` is much more readable than `generateEventName('fs', 'write')`.

**Comment by kraman** [comment]
@cbrichford Please take a look

**Comment by kraman** [comment]
The extra method is a few extra characters to write, but I think it would allow for future changes to the name to be transparently handled. The method may also be extended to encode additional metadata into the internal representation. I don't have a good use-case for that yet tho.

**Comment by cbrichford** [comment]
@kraman The original reason I suggested using a method to generate the event name is to allow the async-tracker api to enfource uniqueness of event names.  Your implementation does not currently do this, but can be easily be extended to do so by just appending a counter to the generated event name.  

Also, making generateEventName return a unique integer may enable future optimizations.

**Comment by kraman** [comment]
Numeric identifiers make sense.

**Pull request merged**
